pipeline
{
    agent none 
    stages 
    {
        stage('Backend') 
        {
         agent
         {
            image 'maven:3.8.1-adoptopenjdk-11'
         }
         steps 
         {
            sh 'mvn --version'
         }
        }
        stage('Frontend') 
        {
         agent
         {
            image 'node:16-alpine'
         }
         steps 
         {
            sh 'node --version'
         }
        }
    }
}
